// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_YMc1c6Nm3E8mxE0nXnSLp7y1Rhzr7pc',
    appId: '1:272932567784:web:9a8f7fef31f6b03581a75d',
    messagingSenderId: '272932567784',
    projectId: 'coinid-5e503',
    authDomain: 'coinid-5e503.firebaseapp.com',
    storageBucket: 'coinid-5e503.firebasestorage.app',
    measurementId: 'G-Q6454835C2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAaQQBkc9cCQv0sF0dYQxGBmW8qDgpBf8',
    appId: '1:272932567784:android:fb12ddc2130bef1381a75d',
    messagingSenderId: '272932567784',
    projectId: 'coinid-5e503',
    storageBucket: 'coinid-5e503.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfXzSAU0pCJVqSywoA0joObIjwTCsAGfs',
    appId: '1:272932567784:ios:9a8e5e52e6de87c981a75d',
    messagingSenderId: '272932567784',
    projectId: 'coinid-5e503',
    storageBucket: 'coinid-5e503.firebasestorage.app',
    iosBundleId: 'com.coinidentifier.app',
  );
}
