import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:math';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure
import 'services/config_service.dart'; // The file we created in Step 1
// -------------------

import 'package:coinidentifier/revenueCat.dart';
import 'package:coinidentifier/view/SplashScreen.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:image_picker/image_picker.dart';
import 'package:camera/camera.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:google_generative_ai/google_generative_ai.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:purchases_flutter/purchases_flutter.dart';

List<CameraDescription> cameras = [];

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarIconBrightness: Brightness.light,
    ),
  );

  // --- 1. INITIALIZE FIREBASE ---
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // --- 2. INITIALIZE CONFIG SERVICE ---
  await ConfigService().initialize();

  try {
    cameras = await availableCameras();
  } catch (e) {
    debugPrint('Error getting cameras: $e');
  }

  final prefs = await SharedPreferences.getInstance();
  if (prefs.getInt('scansLeft') == null) await prefs.setInt('scansLeft', 3);
  if (prefs.getBool('isPremium') == null) await prefs.setBool('isPremium', false);

  runApp(const CoiniumApp());

  // RevenueCat init can stay here or move up, either is fine
  RevenueCatService().initialize();
}

class CoiniumApp extends StatelessWidget {
  const CoiniumApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Coinium',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        brightness: Brightness.dark,
        primaryColor: const Color(0xFF13EC5B),
        scaffoldBackgroundColor: const Color(0xFF102216),
        fontFamily: 'Manrope',
        colorScheme: const ColorScheme.dark(
          primary: Color(0xFF13EC5B),
          secondary: Color(0xFF92C9A4),
          surface: Color(0xFF193322),
        ),
        appBarTheme: const AppBarTheme(
          backgroundColor: Colors.transparent,
          elevation: 0,
          systemOverlayStyle: SystemUiOverlayStyle.light,
        ),
        textTheme: const TextTheme(
          headlineLarge: TextStyle(
            fontSize: 32,
            fontWeight: FontWeight.w800,
            letterSpacing: -0.5,
            color: Colors.white,
          ),
          headlineMedium: TextStyle(
            fontSize: 22,
            fontWeight: FontWeight.w700,
            letterSpacing: -0.3,
            color: Colors.white,
          ),
          bodyLarge: TextStyle(
            fontSize: 16,
            fontWeight: FontWeight.w400,
            color: Colors.white,
          ),
        ),
      ),
      home: const SplashScreen(),
    );
  }
}

// ============================================================================
// Prompts (Kept exactly as you had them)
// ============================================================================

String getPromptForType(String type) {
  switch (type.toLowerCase()) {
    case 'coin':
      return '''
Analyze this coin image and provide detailed information:
**Name**: (Full name of the coin)
**Country**: (Country of origin)
**Year**: (Year minted, if visible)
**Denomination**: (Face value)
**Metal/Composition**: (If identifiable)
**Obverse/Reverse details**: (Key features, legends)
**Mint mark**: (If visible)
**Notes**: (Varieties, errors, historical context)
''';
    case 'banknote':
      return '''
Analyze this banknote image and provide details:
**Name**: (Type of banknote)
**Country**: (Issuing country)
**Year/Series**: (Year or series)
**Denomination**: (Face value)
**Security features**: (Watermark, microprinting, security thread)
**Obverse/Reverse details**: (Portraits, buildings, scenery)
**Notes**: (Varieties, signatures, serial ranges)
''';
    case 'medal':
      return '''
Analyze this medal image and provide details:
**Name**: (Name of the medal)
**Type**: (Military/Civilian/Sports/Commemorative/etc.)
**Country/Issuer**: (Organization or government)
**Year**: (Year of issue)
**Design details**: (Obverse/Reverse)
**Ribbon/Attachment**: (If visible)
**Notes**: (Award criteria, variants)
''';
    case 'token':
      return '''
Analyze this token or artifact image:
**Name/Type**: (Transit token, gaming token, commemorative, artifact)
**Origin**: (Country/region)
**Era/Period**: (Approximate date)
**Material**: (Metal, alloy, other)
**Design details**: (Obverse/Reverse)
**Notes**: (Usage, issuer, known sets)
''';
    default:
      return getPromptForType('coin');
  }
}